name: pysemitip
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  # Core Python
  - python=3.12
  
  # Required packages for current functionality
  - pyyaml>=6.0
  
  # Scientific computing (for future SEMITIP calculations)
  - numpy>=1.21.0
  - scipy>=1.7.0
  
  # Data analysis and visualization (for future analysis features)
  - matplotlib>=3.5.0
  - pandas>=1.3.0
  
  # Development and testing tools
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - black>=22.0.0
  - flake8>=5.0.0
  - mypy>=0.991
  
  # Documentation
  - sphinx>=5.0.0
  - sphinx_rtd_theme>=1.0.0
  
  # Jupyter for analysis and examples
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  
  # Package management
  - pip>=22.0.0
  
  # Additional packages via pip
  - pip:
    - dataclasses-json>=0.5.7  # For enhanced dataclass serialization
    - types-PyYAML>=6.0.0      # Type stubs for mypy
