# SEMITIP MultPlane 模擬參數配置檔
# 自動從 fort.9 檔案轉換
# 版本: 1.0
# 模擬類型: MultPlane

version: '1.0'
simulation_type: MultPlane
environment:
  temperature: 0.0
  dielectric_constant: 1.0e+18
tip:
  shank_slope: 1.0
  separation: 1.0
  radius: 1.0
  protrusion_radius: 0.0
  contact_potential: 0.0
  position:
    x: 0.0
    y: 0.0
  fermi_energy: 0
semiconductor:
  regions: []
  electron_affinity: 0
surface:
  regions:
  - id: 1
    first_distribution:
      density: 0.0
      neutrality_level: 0.006
      fwhm: 0.028
      centroid_energy: 0.0635
    second_distribution:
      density: 0.643
      neutrality_level: 0.081
      fwhm: 0.172
      centroid_energy: 0.341
  temperature_dependence: false
grid:
  mirror_plane: true
  radial_points: 12.9
  vacuum_points: 300.0
  semiconductor_points: 0
  angular_points: 440000000000000.0
  initial_grid_size: 0.125
computation:
  scaling_steps: 0
  max_iterations:
  - 1.625
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  convergence_parameters:
  - 0.0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  charge_density_table_size: 0.0
voltage_scan:
  points: 0
  start_voltage: -2.5
  end_voltage: 2.5
  modulation_voltage: 5000
  negative_ramp: 2
  positive_ramp: 0
multplane_specific:
  vacuum_width: 0.5
  vacuum_spacing: 0
  max_energies:
    light_hole: 40000
    heavy_hole: 20000
    split_off: 10000
    conduction_band: 0
  compute_all_bands: true
output:
  basic_output: false
  equipotential_contours: false
  full_potential: false
  num_contours: 0
  contour_spacing: 0
  contour_angle: 0
