# SEMITIP MultInt 模擬參數配置檔
# 自動從 fort.9 檔案轉換
# 版本: 1.0
# 模擬類型: MultInt

version: '1.0'
simulation_type: MultInt
environment:
  temperature: 0.0
  dielectric_constant: 1.0e+18
tip:
  shank_slope: 1.0
  separation: 1.0
  radius: 1.0
  protrusion_radius: 0.0
  contact_potential: 0.0
  position:
    x: 0.0
    y: 0.0
  fermi_energy: 440000000000000.0
semiconductor:
  regions: []
  electron_affinity: 0
surface:
  regions:
  - id: 1
    first_distribution:
      density: 0.0
      neutrality_level: 0.006
      fwhm: 0.028
      centroid_energy: 0.0635
    second_distribution:
      density: 0.643
      neutrality_level: 0.081
      fwhm: 0.172
      centroid_energy: 0.341
  temperature_dependence: false
grid:
  mirror_plane: true
  radial_points: 0.0
  vacuum_points: 1.0e+18
  semiconductor_points: 1.42
  angular_points: 0.0
  initial_grid_size: 0.006
computation:
  scaling_steps: 0
  max_iterations:
  - 0.0635
  - 0
  - 0
  - 0
  - 0
  convergence_parameters:
  - 0.643
  - 0
  - 0
  - 0
  - 0
  charge_density_table_size: 0.081
voltage_scan:
  points: 0
  start_voltage: 0
  end_voltage: 2.0
  modulation_voltage: 0.0
  negative_ramp: 0.0
  positive_ramp: 0.0
multint_specific:
  parallel_wavevectors: 0.125
  energy_points: 0.25
  expansion_factor: 1.625
  semiconductor_depth_fraction: 0.0
output:
  basic_output: false
  equipotential_contours: false
  full_potential: false
  num_contours: 2
  contour_spacing: 12.9
  contour_angle: 300.0
